mqtt:
  host: "broker.emqx.io"
  port: 1883
  clientID: "go_mqtt_client"
  user: "emqx"
  password: "public"
  debug: false
  topic: "chat/message"
serv:
  port: ":5000"
redis:
  host : "localhost:6379"
  password : ""