apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: amirhossein21/notifier
        resources:
        ports:
        - containerPort: 5000
