apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: amirhossein21/notifier
        ports:
        - containerPort: 8080
      - name: redis
        image: bitnami/redis
        ports:
          - containerPort: 3678
